server:
 port: 8081

spring:
 application:
  name: Company-management
 
#eureka:
# client:
#  register-with-eureka: true
#  fetch-registry: true
#  server-url:
#   default-zone: http://localhost:8761/eureka/
# instance:
#  hostname: localhost